app = "demochat-api"

[build]
  dockerfile = "api/Dockerfile.prod"

[env]
  RACK_ENV = "production"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  RAILS_SERVE_STATIC_FILES = "enabled"

[deploy]
  release_command = """
    echo "Debugging information:" &&
    echo "Ruby version: $(ruby -v)" &&
    echo "Rails version: $(rails -v)" &&
    echo "Current directory: $(pwd)" &&
    echo "Environment variables:" &&
    env | grep RAILS &&
    echo "Gem list:" &&
    gem list &&
    echo "Database configuration:" &&
    cat config/database.yml &&
    bundle exec rails db:create db:migrate --trace
  """
  wait_timeout = 300

[experimental]
  private_network = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[regions]
  primary = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.cors_origins]]
  origin = "https://front-sigma-three.vercel.app"
  methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  allowed_headers = ["*"]
  credentials = true
